apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eiraos-worker
spec:
  podSelector:
    matchLabels:
      app: eiraos-worker
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
